function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 15-Feb-2024 18:37:57

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
h0=axes('Parent',figure1,'Position',[0.076875 0.421185372005044 0.871875 0.433795712484237]);

% Create axes
h1=axes('Parent',figure1,'Position',[0.028125 0.421185372005044 0.025 0.435056746532156]);

% Create axes
h2=axes('Parent',figure1,'Position',[0.076875 0.868852459016393 0.871875 0.0466582597730139]);

% % Create axes
% h3=axes('Parent',figure1,'Position',[0.07625 0.075662042875158 0.871875 0.238335435056746]);;

end

